config/routes.rb
URLshortener::Application.routes.draw do

  get ":link",    to: "links#show"
  resources :links, only: [:create, :destroy]

  root :to => 'links#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url, :title

  validates :url, :title, uniqueness: true
  validates :url, presence: true
  validate  :validate_url

  # =================================================
  # ================ Class methods ==================
  # =================================================

  # Generates a 6-digit unique code for links
  #
  # Returns the alphanumeric 6-digit code
  def self.generate_code
    code = SecureRandom.hex(3)
    while !Link.where(title: code).blank?
      code = SecureRandom.hex(3)
    end
    return code
  end

  # Creates the Link instance with the given title or a generated token
  #
  # url - the String of the URL to link to
  # title - the String alias of the shortened URL
  #
  # Creates the Link object with the given attributes
  def self.build_link(url, title = "")
    processed_title = title.to_s.gsub(" ","")
    processed_title = Link.generate_code if title.blank?

    link = Link.new(url: url, title: processed_title)

    if url_exists?(url)
      Link.where(url: url).first
    else
      link
    end
  end

  # Determines if a URL has previously been saved
  #
  # url - the String URL to verify
  #
  # Returns true if that exact URL has been saved before
  def self.url_exists?(url)
    !Link.where(url: url).blank?
  end

  # Determines if a title (alias) has previously been used
  #
  # title - the String alias of the URL to verify
  #
  # Returns true if that exact title has been used before
  def self.title_exists?(title)
    !Link.where(title: title).blank?
  end

  # Finds the link that has been created with a given URL
  #
  # url - the String url of the link to search
  #
  # Returns the title of the link that matches the URL provided
  def self.existing_link(url)
    Link.where(url: url).first.title
  end

  # =================================================
  # ============== Instance methods =================
  # =================================================

  # Verifies if a url is in the right format
  #
  # Adds errors to the object if it has an invalid url
  def validate_url
    uri = URI.parse(self.url)
    %w( http https ).include?(uri.scheme)
  rescue URI::BadURIError
    self.errors.add(:url, "is not in the right format")
  rescue URI::InvalidURIError
    self.errors.add(:url, "is not in the right format")
  end

  # TODO: Verify that a URL has not already been shortened. If it has, return the original shortened URL

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @links = Link.all.reverse
    @link = Link.new
    @shortened_link = params[:shortened_link]
  end

  def show
    existing_link = Link.where(title: params[:link]).first
    if existing_link
      Link.increment_counter :hits, existing_link.id
      redirect_to existing_link.url
    else
      redirect_to root_path, alert: "The requested link doesn't exist"
    end
  end

  def create
    if Link.url_exists?(params[:link][:url])
      @shortened_link = "#{request.protocol}#{request.host_with_port}/#{Link.existing_link(params[:link][:url])}"
      respond_to do |format|
        format.json { render :json => @link.to_json }
        format.js {
          flash.now[:info] = 'That link already exists',
          @shortened_link
        }
      end
    else
      @link = Link.build_link(params[:link][:url], params[:link][:title])

      respond_to do |format|
        if @link.save
          @shortened_link = "#{request.protocol}#{request.host_with_port}/#{@link.title}"
          format.json { render :json => @link.to_json }
          format.js {
            flash.now[:success] = 'Your shortened link was created successfully',
            @shortened_link
          }
        else
          format.html {
            redirect_to root_path,
            alert: @link.errors.full_messages.to_sentence
          }
          format.json { render :json => {error: 'unprocessable entity'}.to_json }
          format.js {
            flash.now[:alert] = @link.errors.full_messages.to_sentence
          }
        end
      end
    end
  end

  def destroy
    Link.destroy params[:id]
    redirect_to root_path, flash: {warning: "The link has been deleted"}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  .row.text-center
    = content_tag :div, data: {alert: ''}, class: "alert-box #{name}" do
      = msg
      = link_to '&times;'.html_safe, '#', class: 'close'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Shortly - The best URL shortener</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="flash">
      <%= render partial: 'layouts/flash', locals: { flash: flash } %>
    </div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
<div class="debug_zone">
  <p>Params: <%= params.to_json %></p>
  <p>Flash: <%= flash.to_json %></p>
  <p>Flash message: <%= flash.each {|name, msg| msg.to_json } %>
</div>
  </body>
</html>

app/views/links/create.js.erb
$('.flash').html('<%= j render(partial: "layouts/flash", locals: { flash: flash }).html_safe %>');
$('.flash').toggle();
$('.result').slideUp('fast', function() {
  $('.result').css('display', 'none');
  $('#shortened_link').html('<%= j @shortened_link %>');
  $('#shortened_link').after('<a href="<%= @shortened_link %>"<span class="success radius label">Go</span></a>');
});
$('.result').slideDown('fast');
$('html, body').animate( {scrollTop: 300}, 100);
// $('html, body').animate( {scrollTop: $('#shortened_link').offset().top - $(window).height()}, 100);
$('#shortened_link').selectText();

app/views/links/index.html.haml
.row
  .small-12.columns.text-center
    %h1
      = link_to "Shortly", root_path

= form_for(@link, remote: true, html: {:'data-abide' => '' }) do |f|
  .row
    .small-12.medium-8.medium-offset-2.large-6.large-offset-3.columns.input-wrapper
      = f.label :url do
        = 'URL to shorten <small>Required</small>.'.html_safe
      = f.url_field :url, autofocus: true, required: true, placeholder: "http://en.wikipedia.org/wiki/URL_shortening"
      %small.error Valid URL required
  .row
    .small-6.small-offset-3.medium-4.medium-offset-4.large-4.large-offset-4.columns
      = f.label :title do
        = 'Pick an alias <small>Optional</small>'.html_safe
      = f.text_field :title, placeholder: "alias"
  .row
    .small-6.small-centered.medium-3.large-3.large-centered.columns
      %label.text-center#time_label Expires: 15 min.
      %input#time_slider{type: "range", min: 0, max: 4, value: 0, data: {highlight: true}}
    %br
    .small-6.small-centered.medium-3.large-3.columns
      = f.submit "Shorten", class: "button expand"

.row.result
  .small-12.large-centered.columns.text-center
    %h3#shortened_link
      = @shortened_link.to_s
    = link_to '<span class="success radius label">Go</span>'.html_safe, @shortened_link.url if @shortened_link
    %span.secondary.radius.label Copy

- if @links
  .row
    %hr
    .small-12.large-6.large-centered.columns
      %h3.text-center Available links
      .small-6.columns.text-center
        %a.subheader#by_date by date
      .small-6.columns.text-center
        %a.subheader#by_hits by hits
      .row
        %table#link_list
          %thead
            %th.text-center Hits
            %th.text-center Alias
            %th.text-center Created
            %th
          %tbody
            -@links.each do |link|
              %tr
                %td.text-center= link.hits
                %td= link_to link.title, link.url, data: { date: link.created_at.to_i }, target: 'blank'
                %td.text-center= link.created_at.strftime('%b %d, %Y')
                %td.delete_icon.text-center= link_to '<i class="fi-x right"></i>'.html_safe, link_path(link.id), method: :delete